### ISSUE TITLE
Multiline comment with changed background color

### ISSUE THREAD

**Issue by marklnz** [omsharp/BetterComments#15]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 2.0.47

### Description
First of all, I love this extension - it's the best of it's type that I've used. I like the support for multi line comment styling support in particular. However when doing a multiline TODO comment, which I've styled with a background color that's not the same as the editor background, the first line of the comment has the background color extended all the way to the left margin of the editor. The remaining lines do not. Additionally, the closing multi line comment tag (*/) is not highlighted/styled.

Here's an example:

![image](https://user-images.githubusercontent.com/12192572/27462299-9a2a6cba-5774-11e7-8f49-2b5f987c7382.png)

The closing comment tag is unstyled regardless of whether it's on the same line as the last of the comments, or the next line.

### Steps to recreate
1. Change the background color of a comment style to be different to the color of the editor surface
2. Add a multiline comment

### Current behavior
The first line of a multi-line comment is highlighted all the way from the left margin to the opening cvomment tag, and the other lines are not. Additionally the closing comment tag is not styled at all.

### Expected behavior
The first line of a multi-line comment should not be highlighted between the left margin and the opening cvomment tag, so that it is consistent with the other lines. Additionally the closing comment tag should be styled.

**Comment by omsharp** [comment]
I'm glad you like the extension and that you find it useful.

As of now, handling the background is not part of Better Comments. It's VS that handles it and Better Comments has nothing to do with the background color.

However, this could be a feature request.

**Comment by omsharp** [comment]
Thanks for the feedback. I'm glad you like the extension and that you find it useful.

Strange behavior! 

When using "todo" (all small) the background works perfect. 
![image](https://user-images.githubusercontent.com/1245060/27505474-e660f61c-58a0-11e7-93f6-74d4d0269022.png)

If any of the letters is capital, then it behaves like described in this issue.
![image](https://user-images.githubusercontent.com/1245060/27505482-088fc4f2-58a1-11e7-8dca-2efa0508b333.png)

There might be some kind of conflict between Better Comments's Task and VS's. Not sure though. I'll try to look into it.

**Comment by omsharp** [comment]
I found the problem. It's a bug in **_Better Comments_** and has nothing to do with **_VS_**. 
I'll ship an update as soon as I work it out.

**Comment by marklnz** [comment]
Works like a charm! :)
