### ISSUE TITLE
Extension Options do not display correctly

### ISSUE THREAD

**Issue by fourpastmidnight** [omsharp/BetterComments#17]
### Installed product versions
- Visual Studio: Visual Studio 2017 Professional
- This extension: 2.0.48

### Description
The extension's options do not display correctly in the VS Tools|Options dialog. All checkboxes are missing their labels; the dropdown list is missing its items.

### Steps to recreate
1. Install extension
2. Open Tools|Options and navigate to Better Comments
3. None of the extension's options have text labels and the dropdown is missing all items.

### Current behavior
None of the extension's options have text labels and the dropdown list is missing all items.

### Expected behavior
The options should have text labels and the dropdown list should have items.

**Comment by omsharp** [comment]
Hey @fourpastmidnight, do you still have the issue?

**Comment by fourpastmidnight** [comment]
I haven't seen any updates for this extension, and since VS seems to run very slowly with this extension enabled and with Resharper installed, I disabled it. (I think I would prefer your extension, if I could set the options.)

I'll check for an update and if there's one, I'll report back. Otherwise, the last time I looked, this was still an issue.

**Comment by fourpastmidnight** [comment]
I'm not sure if your extension auto-updates, but I checked and I do have the latest version. There have also been several minor releases of VS, and I'm on the latest of that, too. I re-enabled your extension, and the Tools | Options page for your extension seems to be displaying properly now.

Looks good!

Thank you very much.

**Comment by omsharp** [comment]
Welcome, and I'm glad to hear that. 

It does auto update on VS2017.

Thanks for the feedback.
