### ISSUE TITLE
Does not work with Visual Studio 2017

### ISSUE THREAD

**Issue by devtrix** [omsharp/BetterComments#18]
### Installed product versions
- Visual Studio: [example 2017 Professional]
- This extension: [example 2.0.48]

### Description
1. Withing Visual Studio 2017, in the Extensions update window, there is a pop up window for a split second and disappears without any error message.

2. The VSIX only supports Visual Studio 2015.

**Comment by omsharp** [comment]
I reuploaded the vsix. Try it now.
