### ISSUE TITLE
Comments are not colored when indented

### ISSUE THREAD

**Issue by Karpfador** [omsharp/BetterComments#19]
### Installed product versions
- Visual Studio: Community 2017, 15.3.2
- This extension: 2.0.48

### Description
The extension only works with code that is not indented. This has been the case for more than a month

![image](https://user-images.githubusercontent.com/24807827/29814698-8c9db222-8cae-11e7-81f8-7f8c52caf5f8.png)

**Comment by omsharp** [comment]
Hi @Karpfador ,

Please update to the latest version (2.1) and let me know if your problem is solved or not.

**Comment by Karpfador** [comment]
Now all of them work except the //TODO

Only the `//T` part of the comment gets colored

**Comment by Karpfador** [comment]
I'm using TypeScript. The screenshots are also showing react code, so I am mainly working with `.tsx` files

**Comment by omsharp** [comment]
Sorry, but for now TypeScript and React are not supported. 

I'll have to close this issue, since it's not really in scope of the project.

You can open a new [Feature Request] issue to add support for those two in future.

**Comment by Karpfador** [comment]
TypeScript IS Javascript. And that is supported. There is no difference in the comments except for the weird one you see in the second picture.

**Comment by omsharp** [comment]
Is it the same with JavaScript ( .js files )?

**Comment by omsharp** [comment]
Ok, I'm sorry for the quick reply, now that I checked .js files, I see a bug with Task comments.

Will work on it as soon as I can.

Sorry again, and thanks for the good feedback :)

**Comment by omsharp** [comment]
@Karpfador, please update to the latest version and let me know the results.

**Comment by Karpfador** [comment]
Great. Thank you

**Comment by omsharp** [comment]
You're welcome.
