### ISSUE TITLE
[Feature Request] Change only the color of the "Todo" Keyword.

### ISSUE THREAD

**Issue by IceSentry** [omsharp/BetterComments#2]
Instead of coloring the entire comment it would be nice to have the option to only change the color of the keyword. For example, "//TODO: ..." instead of coloring everything yellow only color the "TODO:" part of the comment.

**[Edit by @omsharp : The user defined classifications feature request is moved to it's own #8 ]**
I'm not sure entirely how this works, but also letting user define custom keywords would be a nice feature to have. This might be a visual studio specific thing though.

I can try to implement this myself, but I don't really have any experience with extension making for visual studio.

**Comment by omsharp** [comment]
I'll try to add an option in the _Better Comments_ options page (a CheckBox) to let the user choose whether to change the whole comment or just the TODO keyword. I have an idea in my head on how to do it. Not sure if the implementation will be straight forward though.

For the user defined keyword/classification thing, this was a feature I wanted to have at the beginning, I wanted to let the user define the keywords and make classifications as needed, but then I decided to keep it simple while keeping the idea in mind for future tinkering on the project. I already have a way to implement it, but I have some performance concerns about it. Will see how it goes. 

As soon as I get some free time on my hands I'll happily look into it. I haven't been able to do anything on this project lately. I have a bunch of other improvements and features I want to add to the project. And I can't wait to get back on it..


Thanks for the awesome feedback.

**Comment by IceSentry** [comment]
Awesome! I'd just like to add that I was looking for something like this for a while and I think this should be a default feature of vs. You did a great job!

**Comment by omsharp** [comment]
Dude! I'm super glad to hear that. Thanks.

**Comment by omsharp** [comment]
Hey, @IceSentry.

Check out version 1.3, it's up. 

Added an option to color only the "Todo" keyword and not the whole task comment, also now you can underline important comments.

I hope you don't mind, I took the liberty to change this issue is title to "[Feature Request] Change only the color of the "Todo" Keyword." , just so I can close it, and opened a new one for the user defined/custom keywords feature.

**Comment by IceSentry** [comment]
That's awesome. I'm looking in the code and I'm not sure where exactly you actually do the color changing. Could you direct me where this happens. I think I understand the way you tag the comments and the keywords, but I can't see where the actual color change happens. 

I have been learning c# for a while now but I have no idea how visual studio extensions work and I'd like to help or at least understand what is happening in your code.

Do you know of any documentation I could read on visual studio extensions similar to yours?
