### ISSUE TITLE
[Feature Request] Customize keywords

### ISSUE THREAD

**Issue by Angelinsky7** [omsharp/BetterComments#20]
It would be great if it was possible to customize the 4 different keyword...
Like for example : 

```
! => note
? => question
todo => todo
x => suppress
```

if we could have a new tab in the options to change them...
Thanks in advance

**Comment by Angelinsky7** [comment]
change title

**Comment by omsharp** [comment]
Sorry, I don't get what you mean exactly! 

Could you elaborate more please? Is it customizing the token itself? or just the name?

**Comment by Angelinsky7** [comment]
Sorry,
I would like to customize the token, not use "!" but "Note" (Case ignored) instead....
Because "!" is not in my good practise but "note(username): some random texte" is..

i aslo use `todo(username): a todo text` and `question(username): ask a question` etc....
and the todo part is working great.

P.S: you can completly ignore the `(username)` part, it was just here for you to see what i was talking about

**Comment by omsharp** [comment]
Thanks for the elaborations. Now I see what you mean, and it's pretty much something I had in mind since the start of the project, just didn't get the time to work on it. Hopefully will do soon.

**Comment by omsharp** [comment]
The ability to use custom keywords are now available, as of V2.1.
