### ISSUE TITLE
No strike-through for double comments in VB.Net

### ISSUE THREAD

**Issue by TimboJones** [omsharp/BetterComments#22]
### Installed product versions
- Visual Studio: 2015 Enterprise
- This extension: 2.0.48

### Description
Everything works just perfectly fine, even 'x as Comment will strike the comment through. However if I double comment it with '' it just doesn't work. That's rather inconvinient, cause we use that to mark old code and with a double comment we can easily re-insert whole blocks 

### Steps to recreate
1. start VB.Net project
2. press CTRL + K,C twice
3. nothing happens
4. replace the second ' with a X
5. everything happens

### Current behavior
Comment is neither gray nor striked through

### Expected behavior
Comment should be gray (or whatever I defined the color as) and be striked through

**Comment by omsharp** [comment]
It's disabled by default

![image](https://user-images.githubusercontent.com/1245060/30705926-2664060e-9ef7-11e7-888b-a6b27563438c.png)

**Comment by TimboJones** [comment]
Aahh thanks a bunch! I thought I did that, maybe I didn't save. 

sorry for the issue then!

**Comment by omsharp** [comment]
Welcome.
