### ISSUE TITLE
Missing options text

### ISSUE THREAD

**Issue by LoghamLogan** [omsharp/BetterComments#3]
### Installed product versions
- Visual Studio: 2015 CE
- This extension: 1.1 (1.1.9 on msdn?)

### Description
Options text is missing/does not show next to option boxes.

### Steps to recreate
1. Open Tools->Options...
2. Better Comments->Font Options
3. Text is missing ![screenshot](http://i.imgur.com/JN28vNB.png)

### Current behaviour
No descriptive name/titles are displayed for options.

### Expected behaviour
Options should have descriptive names/titles.

**Comment by omsharp** [comment]
Thanks for the feedback.

Well, the options page does have labels. That I'm sure of. Not sure why not appearing in your case though! Will try to look into it as soon as I get the time.

![image](https://cloud.githubusercontent.com/assets/1245060/16211932/01c82d68-3745-11e6-851b-45d3339accfc.png)

**Comment by omsharp** [comment]
Does it happen with any other extension? Or just _Better Comments_?

Is your VS install clean? Do you have any other extensions or add-ons that you might suspect being a reason for that behavior?

**Comment by omsharp** [comment]
I'm afraid I'll have to close this.

**Comment by omsharp** [comment]
I'm reopening this issue. There's another user facing the same issue.

@LoghamLogan, pleas go to Issue #6  we might be able to solve it if we can find what's common in both of your cases. You'r cooperation will be much appreciated.
