### ISSUE TITLE
Updates to marketplace.visualstudio.com, but there are no changes here?

### ISSUE THREAD

**Issue by MichaelGoulding** [omsharp/BetterComments#36]
Are there new fixes being made that just aren't being pushed here anymore?  I've seen updates to the extension several days in the past month, but no updates there to know what's being changed.

https://marketplace.visualstudio.com/items?itemName=OmarRwemi.BetterComments

**Comment by omsharp** [comment]
Actually it was only updated twice I think. I added a way to get feedback. Nothing changed on the extension itself tho.

The repo is updated now, and in sync with the latest market build.
