### ISSUE TITLE
Visual Studio 2022 support?

### ISSUE THREAD

**Issue by collinbarrett** [omsharp/BetterComments#41]
### Installed product versions
- Visual Studio: 2022 Enterprise
- This extension: N/A

### Description
Is there a version of this extension available or being worked on that is supported in Visual Studio 2022? I love this extension, but the current version in the Marketplace does not seem to support 2022.

Thanks!

**Comment by SirTwsted** [comment]
Bump +1

**Comment by farangkao** [comment]
CodeRush from DevExpress does have this Feature (plus more), however CodeRush is not free (but also not expensive)
If you don't have ReSharper, then i recommend CodeRush anyway as a helper Addin.

The Feature is called "Rich Comments"
https://docs.devexpress.com/CodeRushForRoslyn/120417/visualization-tools/rich-comments#highlight-comments-in-color

**Comment by collinbarrett** [comment]
Ah, nice. I'm a ReSharper user. I haven't seen a feature like this in ReSharper, and probably wouldn't want to run it in addition to CodeRush (slow and double/overlapping paid products).

**Comment by Bengkel** [comment]
I pulled the repo, created a new installer project in VS 2022 and copied all the files from this repo BetterComments folder  (except the packages.config and the csproj file) and copied it in the new project. Build and install it. Works fine!

**Comment by SaschaWeisenberger** [comment]
@Bengkel can you maybe fork this project or describe a bit more in detail what you did?

**Comment by aristocratos** [comment]
@collinbarrett @SirTwsted @SaschaWeisenberger I've updated BetterComments to build for 2022 in my fork: https://github.com/aristocratos/BetterComments

Just open the solution, change to release and then build solution.
In ".\BetterComments\bin\x64\Release\" you'll find the "BetterComments.vsix" you can install.

**Comment by SaschaWeisenberger** [comment]
@aristocratos awesome, thanks a lot!

**Comment by omsharp** [comment]
I've built a version specific for 2022, its available on marketplace now.
https://marketplace.visualstudio.com/items?itemName=OmarRwemi.BetterCommentsVS2022

Also the repo now has two branches as follows: 
Branch vs16 : VS2015, VS2017, and VS2019 on a single vsix.
Branch vs17 : VS2022 only.
