### ISSUE TITLE
Color of first 3 chars in Python

### ISSUE THREAD

**Issue by jimp02** [omsharp/BetterComments#5]
### Installed product versions
- Visual Studio:2015 Community
- This extension: 1.1

### Description
In Python source, the first 3 characters of a comment are grayed, or maybe a different opacity.

### Steps to recreate
1. Open a Python source and observe the comments.
    Using the default colors.
    Settings: Consolas font, 0 size offset, Italic is checked, 1 opacity.

### Current behavior
See Description.

### Expected behavior
Entire comment is the same color and opacity.

**Comment by jimp02** [comment]
This is with the Dark theme on Visual Studio. 
Blue and Light themes are OK.

**Comment by omsharp** [comment]
Can you take a snapshot of the issue? Is it something like this?

![image](https://cloud.githubusercontent.com/assets/1245060/16430060/0fea7e42-3d7a-11e6-8ba8-1daab7462d3c.png)

**Comment by jimp02** [comment]
I installed a new Python Tools release yesterday that apparently caused the problem.
I reinstalled Python Tools release 2.2.4 and Better Comments is now working OK.
The problem seems to be fixed.
Thanks for the quick attention to the problem.

**Comment by omsharp** [comment]
You're most welcome.
