### ISSUE TITLE
[Request] Make the extension available for VS 2017

### ISSUE THREAD

**Issue by SvenAelterman** [omsharp/BetterComments#7]
### Installed product versions
- Visual Studio: VS 15 Preview 3
- This extension: N/A
### Description

Can you make a build available for VS "15"
### Steps to recreate
1. Better Comments does not show as an extension for VS "15"

**Comment by omsharp** [comment]
I don't have VS 15 installed currently. I'm not even sure if the VS 15 extension model is the same as VS 2015 or not. 

Anyway, I can see myself the extension for VS 15 for sure. But I'll have to get VS 15 first and I'm not sure I'll get it before the RTM.

**Comment by bramborman** [comment]
@omsharp so the Visual Studio 2017 is out so I hope you didn't forget and will make this great extension available for it. Really missing the colors :/

**Comment by omsharp** [comment]
I'm in a place where Internet connection really sucks. However I'm doing my best to finish downloading the huge VS 2017, and as soon as I finish downloading it I'll make the extension available for sure. hopefully it wouldn't take much longer.

**Comment by omsharp** [comment]
@SvenAelterman @bramborman 

The extension is working on VS2017 now. 

Enjoy the colors  :)
